### ISSUE TITLE
Not a bug just a question

### ISSUE THREAD

**Issue by beyond420** [Project-Sloth/ps-objectspawner#17]
first off love the resource, but had a question. can you make it so we can move the object up and down? or do you have a snippet for it. id really love to be able to move the item in play up and down because sometimes if its on just not flat land all over whatever corner is touch the ground the highest is where the item will sit so sometimes itll be off the ground just alittle bit. thank you for the great resource!

**Comment by MonkeyWhisper** [comment]
You can make it, this is an open source project. 

Looking forward to your PR.
