### ISSUE TITLE
[Suggestion] A checkbox/button to allow floating props like cameras

### ISSUE THREAD

**Issue by DeNtrlPredator** [Project-Sloth/ps-objectspawner#18]
PS-ObjectSpawner is great but its missing one thing. The ability to place props on walls or on ceilings. It would be great to have a checkbox/button that would allow for props to be hung on walls. Some examples are fire alarm switches, Portraits on walls, or security cameras on ceilings/walls.

**Comment by MonkeyWhisper** [comment]
Great idea, send a PR.
