### ISSUE TITLE
Prop Spawning issue and deleting

### ISSUE THREAD

**Issue by Polo4217** [Project-Sloth/ps-objectspawner#4]
Props Will Tripple spawn in live server then you can't delete them.

![FiveM_b2372_GTAProcess_Yt1LF816j8](https://user-images.githubusercontent.com/90496416/177836345-94950fc8-23ee-49a4-9d64-aa817059d50f.jpg)
![FiveM_b2372_GTAProcess_Ex9ersEQgH](https://user-images.githubusercontent.com/90496416/177836365-36467bdd-46c6-4d63-95a2-6e866d1cf372.jpg)

**Comment by MonkeyWhisper** [comment]
Not for support.
