### ISSUE TITLE
/object command

### ISSUE THREAD

**Issue by spinokio** [Project-Sloth/ps-objectspawner#7]
I put sql to my database, the script is started, there are no errors in the console, but I don't have the /object command, I use the latest qbcore, I'm set, god, but I still don't have the command.  I will be glad if you can help me  😉

**Comment by AscendoTuum86** [comment]
Having the same issue, looked at it a few times and still scratching my head. It tells me I don't have permission for the command but I have God perms as well.

**Comment by derTweaky** [comment]
the same

**Comment by MonkeyWhisper** [comment]
Script is working. This is not for support. Join the Discord.

**Comment by AscendoTuum86** [comment]
> Script is working. This is not for support. Join the Discord.

Glad I checked this again since I don't get any notification that this was responded to, but since I have yet to get a response on Discord either, I guess the answer is just "it works"
![image](https://user-images.githubusercontent.com/53923002/188940315-a01d8b52-6411-4f50-bfd2-70863fefa3b0.png)
