### ISSUE TITLE
Not reading god to use /object

### ISSUE THREAD

**Issue by Soldierofthelam** [Project-Sloth/ps-objectspawner#9]
Qbcore did a stupid thing and removed all permissions from the sql and uses fiveM now,
There is no way that I can find to set permissions to god mode to use the function /object.
 Setting god in admin panel is only temporarily and doesn't allow scripts to read it as a sql permission

 And I do have my 
add_principal identifier.fivem:" 00000" group.god 
set as qbcore suggest for newest build

**Comment by CptNoHand** [comment]
Same

**Comment by Soldierofthelam** [comment]
4 months later never replied to an issue and just closes it,....interesting.

**Comment by MonkeyWhisper** [comment]
Hmm. Interesting indeed that you can't figure out how to set yourself as God permission. 

This isn't an issue with our script but an user error. :)

**Comment by Soldierofthelam** [comment]
> Hmm. Interesting indeed that you can't figure out how to set yourself as God permission.
> 
> This isn't an issue with our script but an user error. :)

Trying to be a smart ass while looking dumb,
  If you read my comment above you would of read I already did that, so you comment was as per usual useless. 
Maybe next time actually read a comment and understand the comment before you pop off on gibberish nonsense blaming the user.

**Comment by MonkeyWhisper** [comment]
> > Hmm. Interesting indeed that you can't figure out how to set yourself as God permission.
> > This isn't an issue with our script but an user error. :)
> 
> Trying to be a smart ass while looking dumb, If you read my comment above you would of read I already did that, so you comment was as per usual useless. Maybe next time actually read a comment and understand the comment before you pop off on gibberish nonsense blaming the user.

Sorry to hear you're not competent enough to simple set the correct permissions. You may want to ask these other 515 servers that have a real developer how they're able to do it. 

Best of luck with learning basic convars.
![image](https://user-images.githubusercontent.com/82112471/222927786-ebbf7c8c-9262-411b-b10b-307fcd547b67.png)

**Comment by Soldierofthelam** [comment]
Yea that doesn't work on me, sos hike your skirt down little girl.
 nice try though trying to recover a dumb ass statement.

**Comment by Soldierofthelam** [comment]
> > > Hmm. Interesting indeed that you can't figure out how to set yourself as God permission.
> > > This isn't an issue with our script but an user error. :)
> > 
> > 
> > Trying to be a smart ass while looking dumb, If you read my comment above you would of read I already did that, so you comment was as per usual useless. Maybe next time actually read a comment and understand the comment before you pop off on gibberish nonsense blaming the user.
> 
> Sorry to hear you're not competent enough to simple set the correct permissions. You may want to ask these other 515 servers that have a real developer how they're able to do it.
> 
> Best of luck with learning basic convars. ![image](https://user-images.githubusercontent.com/82112471/222927786-ebbf7c8c-9262-411b-b10b-307fcd547b67.png)

Yea that doesn't work on me, so hike your skirt down little girl.
Funny how the incompetent always reverts to meaningless chatter trying to justify their ideocracy of dumbfound comebacks.
So next time try really really hard and think before your speak.
 No more replies to this individual due to lack of intelligence,
  You have a great day little man:)

**Comment by Soldierofthelam** [comment]
> > > Hmm. Interesting indeed that you can't figure out how to set yourself as God permission.
> > > This isn't an issue with our script but an user error. :)
> > 
> > 
> > Trying to be a smart ass while looking dumb, If you read my comment above you would of read I already did that, so you comment was as per usual useless. Maybe next time actually read a comment and understand the comment before you pop off on gibberish nonsense blaming the user.
> 
> Sorry to hear you're not competent enough to simple set the correct permissions. You may want to ask these other 515 servers that have a real developer how they're able to do it.
> 
> Best of luck with learning basic convars. ![image](https://user-images.githubusercontent.com/82112471/222927786-ebbf7c8c-9262-411b-b10b-307fcd547b67.png)

Yea that doesn't work on me, so hike your skirt down little girl.
Funny how the incompetent always reverts to meaningless chatter trying to justify their idiocracy of dumbfound comebacks.
So next time try really really hard and think before your speak.
 No more replies to this individual due to lack of intelligence,
  You have a great day little man:)
